# Generated by Django 3.2.13 on 2024-03-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.CharField(default='blue', max_length=255),
        ),
    ]
