# Generated by Django 3.2.13 on 2024-03-12 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Pid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Uid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 10, 17, 9, 352506)),
        ),
    ]
