# Generated by Django 3.2.13 on 2024-03-31 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20240331_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 23, 12, 5, 932332)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
